[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "transport-verification-demo"

[services.healthcheck]
path = "/"
timeout = 100
